# Generated by Django 3.2.19 on 2023-06-09 09:37

import colorfield.fields
from django.db import migrations
import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', help_text='Цветовой HEX-код', image_field=None, max_length=18, samples=None, validators=[recipes.validators.hex_field_validator], verbose_name='Цветовой HEX-код'),
        ),
    ]
